apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: siddheshm716/hostelmate-backend:latest
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: hostelmate-config
        - secretRef:
            name: hostelmate-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
  - port: 5001
  selector:
    app: backend
