[master]
# Replace with actual IP from Terraform output
master-node ansible_host=18.61.15.121 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/expt1-key.pem

[workers]
# Replace with actual IPs from Terraform output
worker-node-1 ansible_host=98.130.142.224 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/expt1-key.pem
worker-node-2 ansible_host=16.112.4.130 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/expt1-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
