[master]
# Replace with actual IP from Terraform output
master-node ansible_host=18.61.166.193 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/expt1-key.pem

[workers]
# Replace with actual IPs from Terraform output
worker-node-1 ansible_host=18.60.43.105 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/expt1-key.pem
worker-node-2 ansible_host=40.192.99.159 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/expt1-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
